import type { DayAvailability, Lesson, Teacher, User } from "./types";

export const fmtUzs = (n: number) =>
  n.toLocaleString("en-US").replace(/,/g, " ") + " UZS";

const week = (
  entries: [string, boolean, [string, string][]][]
): DayAvailability[] =>
  entries.map(([day, enabled, ranges]) => ({
    day,
    enabled,
    ranges: ranges.map(([start, end]) => ({ start, end })),
  }));

export const TEACHERS: Teacher[] = [
  {
    id: "t1",
    name: "Aziza Karimova",
    initials: "AK",
    title: "IELTS & Academic English",
    subjects: ["English", "IELTS"],
    specializations: ["IELTS 8.0", "Academic Writing", "Speaking"],
    experienceYears: 6,
    languages: ["English", "Русский", "O‘zbek"],
    bio: "Certified IELTS instructor helping students reach band 7.0+. My lessons are structured, honest, and built around your actual weaknesses — not generic templates.",
    rating: 4.9,
    reviewsCount: 132,
    studentsTaught: 120,
    lessonsTaught: 2400,
    verified: true,
    online: true,
    color: "#7B61FF",
    nextAvailable: "Today · 17:30",
    lessons: [
      { id: "l1", title: "IELTS Speaking Practice", durationMin: 60, priceUzs: 120000, description: "Full mock speaking section with detailed band feedback." },
      { id: "l2", title: "Academic Writing Clinic", durationMin: 60, priceUzs: 120000, description: "Task 1 & Task 2 essay strategy, structure, and live correction." },
      { id: "l3", title: "Trial Lesson", durationMin: 30, priceUzs: 50000, description: "Meet, set your goal, and build a personal plan." },
    ],
    availability: week([
      ["Mon", true, [["09:00", "12:00"], ["15:00", "19:00"]]],
      ["Tue", true, [["09:00", "13:00"]]],
      ["Wed", true, [["14:00", "19:00"]]],
      ["Thu", true, [["09:00", "12:00"], ["15:00", "18:00"]]],
      ["Fri", true, [["10:00", "14:00"]]],
      ["Sat", true, [["10:00", "16:00"]]],
      ["Sun", false, []],
    ]),
  },
  {
    id: "t2",
    name: "Jamshid Mahkamov",
    initials: "JM",
    title: "IELTS & English Teacher",
    subjects: ["English", "IELTS"],
    specializations: ["IELTS 8.0", "General English", "Teens"],
    experienceYears: 3,
    languages: ["English", "O‘zbek"],
    bio: "IELTS 8.0 holder. I focus on practical speaking confidence and exam technique for busy students who need results on a deadline.",
    rating: 4.8,
    reviewsCount: 86,
    studentsTaught: 74,
    lessonsTaught: 1300,
    verified: true,
    online: true,
    color: "#0E0F13",
    nextAvailable: "Tomorrow · 10:00",
    lessons: [
      { id: "l1", title: "General English", durationMin: 60, priceUzs: 90000, description: "Communication-first lessons tailored to your level." },
      { id: "l2", title: "IELTS Preparation", durationMin: 60, priceUzs: 100000, description: "Section-by-section preparation with weekly mock check-ins." },
      { id: "l3", title: "Trial Lesson", durationMin: 30, priceUzs: 40000, description: "A short intro session to see if we are a fit." },
    ],
    availability: week([
      ["Mon", true, [["10:00", "13:00"], ["16:00", "20:00"]]],
      ["Tue", true, [["10:00", "13:00"], ["16:00", "20:00"]]],
      ["Wed", false, []],
      ["Thu", true, [["10:00", "13:00"], ["16:00", "20:00"]]],
      ["Fri", true, [["14:00", "18:00"]]],
      ["Sat", true, [["09:00", "13:00"]]],
      ["Sun", true, [["10:00", "12:00"]]],
    ]),
  },
  {
    id: "t3",
    name: "Madina Rahimova",
    initials: "MR",
    title: "Mathematics · SAT Math",
    subjects: ["Math", "SAT"],
    specializations: ["SAT 780 Math", "Algebra", "Calculus"],
    experienceYears: 5,
    languages: ["English", "Русский"],
    bio: "Math should feel inevitable, not magical. I teach students to see structure — from school algebra to SAT 700+ scores.",
    rating: 5.0,
    reviewsCount: 64,
    studentsTaught: 58,
    lessonsTaught: 980,
    verified: true,
    online: false,
    color: "#1FAD55",
    nextAvailable: "Wed · 14:00",
    lessons: [
      { id: "l1", title: "SAT Math", durationMin: 60, priceUzs: 110000, description: "Strategy, pacing, and problem patterns for the digital SAT." },
      { id: "l2", title: "School Math Support", durationMin: 60, priceUzs: 90000, description: "Algebra, geometry, and calculus — aligned with your curriculum." },
      { id: "l3", title: "Trial Lesson", durationMin: 30, priceUzs: 45000, description: "Diagnostic session and study plan." },
    ],
    availability: week([
      ["Mon", true, [["14:00", "18:00"]]],
      ["Tue", false, []],
      ["Wed", true, [["14:00", "18:00"]]],
      ["Thu", true, [["09:00", "12:00"]]],
      ["Fri", true, [["14:00", "18:00"]]],
      ["Sat", false, []],
      ["Sun", true, [["10:00", "14:00"]]],
    ]),
  },
  {
    id: "t4",
    name: "Sofia Karimova",
    initials: "SK",
    title: "English for Kids & Teens",
    subjects: ["English"],
    specializations: ["Cambridge YLE", "Phonics", "Speaking Clubs"],
    experienceYears: 4,
    languages: ["English", "O‘zbek", "Русский"],
    bio: "Patient, energetic lessons for young learners. Games, stories, and structure — so English becomes the fun part of the day.",
    rating: 4.9,
    reviewsCount: 118,
    studentsTaught: 96,
    lessonsTaught: 1750,
    verified: false,
    online: true,
    color: "#F5A623",
    nextAvailable: "Today · 18:00",
    lessons: [
      { id: "l1", title: "Kids English (7–12)", durationMin: 45, priceUzs: 70000, description: "Playful, structured lessons for young learners." },
      { id: "l2", title: "Teen Speaking Club", durationMin: 60, priceUzs: 80000, description: "Confidence-first conversation practice." },
      { id: "l3", title: "Trial Lesson", durationMin: 25, priceUzs: 30000, description: "Meet the teacher and try a mini-lesson." },
    ],
    availability: week([
      ["Mon", true, [["15:00", "20:00"]]],
      ["Tue", true, [["15:00", "20:00"]]],
      ["Wed", true, [["15:00", "20:00"]]],
      ["Thu", true, [["15:00", "20:00"]]],
      ["Fri", false, []],
      ["Sat", true, [["10:00", "14:00"]]],
      ["Sun", false, []],
    ]),
  },
  {
    id: "t5",
    name: "Bekzod Alimov",
    initials: "BA",
    title: "Programming · Python & Web",
    subjects: ["Programming"],
    specializations: ["Python", "Web Development", "Olympiads"],
    experienceYears: 7,
    languages: ["Русский", "O‘zbek", "English"],
    bio: "Software engineer turned teacher. I teach programming the way it's used at work — projects first, theory as you need it.",
    rating: 4.8,
    reviewsCount: 92,
    studentsTaught: 110,
    lessonsTaught: 1600,
    verified: true,
    online: true,
    color: "#3B82F6",
    nextAvailable: "Today · 19:00",
    lessons: [
      { id: "l1", title: "Python from Zero", durationMin: 60, priceUzs: 100000, description: "Project-based Python for complete beginners." },
      { id: "l2", title: "Web Development", durationMin: 90, priceUzs: 150000, description: "HTML, CSS, JavaScript, React — build and deploy real sites." },
      { id: "l3", title: "Trial Lesson", durationMin: 30, priceUzs: 40000, description: "Assess your level and map a learning path." },
    ],
    availability: week([
      ["Mon", true, [["18:00", "21:00"]]],
      ["Tue", true, [["18:00", "21:00"]]],
      ["Wed", true, [["18:00", "21:00"]]],
      ["Thu", true, [["18:00", "21:00"]]],
      ["Fri", true, [["18:00", "21:00"]]],
      ["Sat", true, [["11:00", "15:00"]]],
      ["Sun", true, [["11:00", "15:00"]]],
    ]),
  },
  {
    id: "t6",
    name: "Nilufar Saidova",
    initials: "NS",
    title: "Russian Language & Literature",
    subjects: ["Russian"],
    specializations: ["Grammar", "School Support", "Adults"],
    experienceYears: 9,
    languages: ["Русский", "O‘zbek"],
    bio: "Nine years of classroom experience. Calm, methodical lessons that turn 'I kind of understand' into confident reading, writing, and speech.",
    rating: 4.7,
    reviewsCount: 54,
    studentsTaught: 65,
    lessonsTaught: 2100,
    verified: false,
    online: false,
    color: "#D946EF",
    nextAvailable: "Thu · 16:00",
    lessons: [
      { id: "l1", title: "Russian for School", durationMin: 60, priceUzs: 80000, description: "Grammar and literature support aligned with school." },
      { id: "l2", title: "Conversational Russian", durationMin: 60, priceUzs: 85000, description: "Speak naturally — for work, study, and daily life." },
      { id: "l3", title: "Trial Lesson", durationMin: 30, priceUzs: 35000, description: "A friendly first meeting and level check." },
    ],
    availability: week([
      ["Mon", false, []],
      ["Tue", true, [["16:00", "19:00"]]],
      ["Wed", false, []],
      ["Thu", true, [["16:00", "19:00"]]],
      ["Fri", true, [["16:00", "19:00"]]],
      ["Sat", true, [["09:00", "12:00"]]],
      ["Sun", false, []],
    ]),
  },
  {
    id: "t7",
    name: "Timur Yusupov",
    initials: "TY",
    title: "Physics · University Admissions",
    subjects: ["Physics"],
    specializations: ["DTM Preparation", "Mechanics", "IB Physics"],
    experienceYears: 8,
    languages: ["O‘zbek", "Русский"],
    bio: "Physics makes sense when it's visual. I prepare students for university admission exams with diagrams, demos, and relentless practice.",
    rating: 4.9,
    reviewsCount: 71,
    studentsTaught: 88,
    lessonsTaught: 1900,
    verified: true,
    online: false,
    color: "#0EA5E9",
    nextAvailable: "Fri · 15:00",
    lessons: [
      { id: "l1", title: "DTM Physics", durationMin: 90, priceUzs: 130000, description: "Intensive preparation for admission physics tests." },
      { id: "l2", title: "School Physics", durationMin: 60, priceUzs: 95000, description: "Mechanics to electromagnetism, step by step." },
      { id: "l3", title: "Trial Lesson", durationMin: 30, priceUzs: 40000, description: "Diagnostic and planning session." },
    ],
    availability: week([
      ["Mon", true, [["15:00", "18:00"]]],
      ["Tue", false, []],
      ["Wed", true, [["15:00", "18:00"]]],
      ["Thu", false, []],
      ["Fri", true, [["15:00", "18:00"]]],
      ["Sat", true, [["10:00", "13:00"]]],
      ["Sun", true, [["10:00", "13:00"]]],
    ]),
  },
  {
    id: "t8",
    name: "Kamila Ergasheva",
    initials: "KE",
    title: "German · A1–B2 & TestDaF",
    subjects: ["German"],
    specializations: ["Goethe-Zertifikat", "TestDaF", "Conversation"],
    experienceYears: 5,
    languages: ["Deutsch", "English", "O‘zbek"],
    bio: "From zero to B2 with structure and humour. Certified Goethe-Institut methods, real conversation from lesson one.",
    rating: 4.8,
    reviewsCount: 47,
    studentsTaught: 52,
    lessonsTaught: 870,
    verified: true,
    online: true,
    color: "#F43F5E",
    nextAvailable: "Tomorrow · 09:00",
    lessons: [
      { id: "l1", title: "German A1–B2", durationMin: 60, priceUzs: 95000, description: "Structured course with Goethe-Institut materials." },
      { id: "l2", title: "TestDaF Preparation", durationMin: 60, priceUzs: 110000, description: "Exam format, timing, and scoring strategy." },
      { id: "l3", title: "Trial Lesson", durationMin: 30, priceUzs: 40000, description: "Meet, assess, plan — auf Deutsch!" },
    ],
    availability: week([
      ["Mon", true, [["09:00", "12:00"]]],
      ["Tue", true, [["09:00", "12:00"], ["17:00", "19:00"]]],
      ["Wed", true, [["09:00", "12:00"]]],
      ["Thu", true, [["17:00", "20:00"]]],
      ["Fri", false, []],
      ["Sat", true, [["10:00", "13:00"]]],
      ["Sun", false, []],
    ]),
  },
];

export const DEMO_STUDENT: User = {
  id: "u-student",
  name: "Jasur Toshev",
  email: "jasur@student.liberum.uz",
  role: "student",
  initials: "JT",
};

export const DEMO_TEACHER: User = {
  id: "t1",
  name: "Aziza Karimova",
  email: "aziza@liberum.uz",
  role: "teacher",
  initials: "AK",
};

export const STUDENT_LESSONS: Lesson[] = [
  {
    id: "les-1",
    teacherId: "t1",
    studentId: "u-student",
    teacherName: "Aziza Karimova",
    studentName: "Jasur Toshev",
    title: "IELTS Speaking Practice",
    date: "Today",
    time: "17:30",
    durationMin: 60,
    priceUzs: 120000,
    status: "starting-soon",
  },
  {
    id: "les-2",
    teacherId: "t2",
    studentId: "u-student",
    teacherName: "Jamshid Mahkamov",
    studentName: "Jasur Toshev",
    title: "General English",
    date: "Thu, Aug 27",
    time: "16:00",
    durationMin: 60,
    priceUzs: 90000,
    status: "scheduled",
  },
  {
    id: "les-3",
    teacherId: "t3",
    studentId: "u-student",
    teacherName: "Madina Rahimova",
    studentName: "Jasur Toshev",
    title: "SAT Math",
    date: "Sat, Aug 29",
    time: "14:00",
    durationMin: 60,
    priceUzs: 110000,
    status: "scheduled",
  },
  {
    id: "les-4",
    teacherId: "t1",
    studentId: "u-student",
    teacherName: "Aziza Karimova",
    studentName: "Jasur Toshev",
    title: "Academic Writing Clinic",
    date: "Tue, Aug 18",
    time: "18:00",
    durationMin: 60,
    priceUzs: 120000,
    status: "completed",
  },
  {
    id: "les-5",
    teacherId: "t5",
    studentId: "u-student",
    teacherName: "Bekzod Alimov",
    studentName: "Jasur Toshev",
    title: "Python from Zero",
    date: "Sat, Aug 15",
    time: "11:00",
    durationMin: 60,
    priceUzs: 100000,
    status: "completed",
  },
];

export const TEACHER_LESSONS: Lesson[] = [
  {
    id: "tles-1",
    teacherId: "t1",
    studentId: "u-student",
    teacherName: "Aziza Karimova",
    studentName: "Jasur Toshev",
    title: "IELTS Speaking Practice",
    date: "Today",
    time: "17:30",
    durationMin: 60,
    priceUzs: 120000,
    status: "starting-soon",
  },
  {
    id: "tles-2",
    teacherId: "t1",
    studentId: "s2",
    teacherName: "Aziza Karimova",
    studentName: "Madina Rahimova",
    title: "Academic Writing Clinic",
    date: "Today",
    time: "19:00",
    durationMin: 60,
    priceUzs: 120000,
    status: "scheduled",
  },
  {
    id: "tles-3",
    teacherId: "t1",
    studentId: "s3",
    teacherName: "Aziza Karimova",
    studentName: "Sofia Karimova",
    title: "Trial Lesson",
    date: "Wed, Aug 26",
    time: "15:00",
    durationMin: 30,
    priceUzs: 50000,
    status: "scheduled",
  },
  {
    id: "tles-4",
    teacherId: "t1",
    studentId: "s4",
    teacherName: "Aziza Karimova",
    studentName: "Bekzod Alimov",
    title: "IELTS Speaking Practice",
    date: "Fri, Aug 21",
    time: "11:00",
    durationMin: 60,
    priceUzs: 120000,
    status: "completed",
  },
];

export const SUBJECTS = ["All subjects", "English", "IELTS", "Math", "SAT", "Programming", "Russian", "Physics", "German"];

export const BOOKABLE_TIMES = ["09:00", "10:00", "11:00", "12:00", "14:00", "15:00", "16:00", "17:00", "17:30", "18:00", "19:00"];
